#ebs csi driver install --> git hub --> examples/kubernetes --> static-provisioning -->manifests--> claim.yaml
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: ebs-static
spec:
  storageClassName: "" # Empty string must be explicitly set otherwise default StorageClass will be set
  # PV name
  volumeName: ebs-static
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 20Gi # we can ask max of 30GB, because our volume is max of 30gb
---
#ebs csi driver install --> git hub --> examples/kubernetes --> static-provisioning --> manifests --> pod.yaml
apiVersion: v1
kind: Pod
metadata:
  name: ebs-static
  labels:
    purpose: "ebs-static-demo"
spec:
  nodeSelector:
    topology.kubernetes.io/zone: us-east-1a
  containers:
  - name: nginx
    image: nginx
    volumeMounts:
    - name: persistent-storage # name can be anything
      mountPath: /usr/share/nginx/html # whatever directory we can place where data is stored # whatever we store in this directory--> it will store in the volume
  volumes: # it request the pvc
  - name: persistent-storage # volumeMounts name volumes name should be same
    persistentVolumeClaim:
      claimName: ebs-static
# ---
# kind: Service
# apiVersion: v1
# metadata:
#   name: nginx-lb
# spec:
#   type: LoadBalancer
#   selector: # labels are used as selectors
#     purpose: "ebs-static-demo"
#   ports:
#   - protocol: TCP
#     port: 80 # service port
#     targetPort: 80
#     nodePort: 30007