apiVersion: v1
kind: Pod
metadata:
  name: nginx # nginx is name of the pod
  namespace: expense # expense is name of the namespace
spec:
  # one pod can contain multiple containers
  containers:
  - name: nginx # name of the container
    image: nginx # name of the image