# kubernetes --> kubernetes --> search as labels
kind: Pod
apiVersion: v1
metadata:
  name: labels
  labels:
    project: expense
    component: backend
    environment: dev
spec:
  containers:
  - name: nginx
    image: nginx
    
