# kubernetes --> kubernetes --> search as secrets
# k8 secret yaml --> spacelift
apiVersion: v1
kind: Secret
metadata:
  name: dotfile-secret
type: Opaque
data:
  username: YWRtaW4=
  password: YWRtaW4xMjM=