# kubernetes --> kubernetes --> search as secrets
# k8 secret yaml --> spacelift
kind: Pod
apiVersion: v1
metadata:
  name: pod-secret
spec:
  containers:
  - name: nginx
    image: nginx
    envFrom:
    - secretRef:
        name: dotfile-secret