# some resource are kept in v1 version, some resource kept in apps/v1 for easy maintanance
apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: nginx
  # these labels are replicaset labels
  labels:
    app: frontend
    tier: web
spec:
  # this is number of replica we required
  replicas: 3
  selector:
    # first match with the replicaset labels with the pod labels
    # replicaset use these labels to find the pods for creating desired number of replicas
    matchLabels:
      app: frontend
      tier: web
  # pod template
  template:
    metadata:
      labels:
        app: frontend
        tier: web
    spec:
      containers:
      - name: nginx
        image: nginx:stable-perl
        #image: nginx