# copied from k8-rbac --> role.yaml
# search in google as k8-rbac --> click on kubernetes
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  namespace: expense
  name: sa-account-reader
rules:
- apiGroups: [""] # "" or empty indicates the core API group or v1. * means all. 
  resources: ["*"] # ["pods"]
  verbs: ["get", "watch", "list"]
---
# rolebinding means attaching roles to the user 
apiVersion: rbac.authorization.k8s.io/v1
# This role binding allows "jane" to read pods in the "default" namespace.
# You need to already have a Role named "pod-reader" in that namespace.
kind: RoleBinding
metadata:
  name: sa-account-reader
  namespace: expense
# we should mention user details
subjects:
# You can specify more than one "subject"
- kind: ServiceAccount
  name: expense-mysql-secret # "name" is case sensitive
  namespace: expense # search as k8 rbac service account --> click on kubernetes --> ctrl F search as  ServiceAccount 
# you should mention the role details 
roleRef:
  # "roleRef" specifies the binding to a Role / ClusterRole
  kind: Role #this must be Role or ClusterRole
  name: sa-account-reader # this must match the name of the Role or ClusterRole you wish to bind to
  apiGroup: rbac.authorization.k8s.io
---
# kubernetes --> kubernetes --> search as pod
apiVersion: v1
kind: Pod
metadata:
  name: service-account-demo # nginx is name of the pod
  namespace: expense # expense is name of the namespace
spec:
  # one pod can contain multiple containers
  serviceAccount: expense-mysql-secret
  initContainers: 
  # Using awscli we are going to fetch the secrets from aws secret manager and store in the .env file in /secret folder
  - name: awscli  # To interact with aws we need awscli
    image: amazon/aws-cli #login to dockerhub --> explore --> search as amazon/aws-cli
    command: ['sh', '-c', "aws secretsmanager get-secret-value --secret-id expense/mysql/creds --query SecretString --output text > /secret/.env"] # search as aws secret get value --> Amazon Aws Documentation and copy and paste in terminal to get extra text(--query SecretString --output text)
    volumeMounts: #seach as kubernetes-->search as emptyDir--> ctrl F emptyDir
    - mountPath: /secret #it mount the /secret folder to secret-volume
      name: secret-volume
  containers:
  - name: nginx # name of the container
    image: nginx # name of the image
    volumeMounts: #seach as kubernetes-->search as emptyDir--> ctrl F emptyDir
    - mountPath: /secret #main container will access the /secret folder from secret-volume
      name: secret-volume
  volumes: #seach as kubernetes-->search as emptyDir--> ctrl F emptyDir
  - name: secret-volume
    emptyDir: {}