# kubernetes --> kubernetes --> search as pod
apiVersion: v1
kind: Pod
metadata:
  name: service-account-demo # nginx is name of the pod
  namespace: expense # expense is name of the namespace
spec:
  # one pod can contain multiple containers
  serviceAccount: expense-mysql-secret
  initContainers: 
  # Using awscli we are going to fetch the secrets from aws secret manager and store in the .env file in /secret folder
  - name: awscli  # To interact with aws we need awscli
    image: amazon/aws-cli #login to dockerhub --> explore --> search as amazon/aws-cli
    command: [ 'sh', '-c', " aws secretsmanager get-secret-value --secret-id expense/mysql/creds --query SecretString --output text /secret/.env" ] # search as aws secret get value --> Amazon Aws Documentation and copy and paste in terminal to get extra text(--query SecretString --output text)
  volumeMounts: #seach as kubernetes-->search as emptyDir--> ctrl F emptyDir
  - mountPath: /secret #it mount the /secret folder to secret-volume
    name: secret-volume
  containers:
  - name: nginx # name of the container
    image: nginx # name of the image
  volumeMounts: #seach as kubernetes-->search as emptyDir--> ctrl F emptyDir
  - mountPath: /secret #main container will access the /secret folder from secret-volume
    name: secret-volume
  volumes: #seach as kubernetes-->search as emptyDir--> ctrl F emptyDir
  - name: secret-volume
    emptyDir: {}